spring:
    config:
        import:
            - file:/config-external/application-api.yml
            - file:/config-external/application-aws.yml
            - file:/config-external/application-path.yml
            - file:/config-external/application-secret.yml
