version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      # 메인 설정 파일
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # 시크릿들 파일 전체 마운트
      - ./prometheus/secrets:/etc/prometheus/secrets:ro

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
